algoritmo "conversaodemoedas"
// Função :
// Autor :
// Data : 8/2/2023
// Seção de Declarações 
var
   R, D: real
   C, Q : inteiro
   
inicio
// Seção de Comandos 

c <- 1

Escreva ("Quantas vezes você quer converter?: ")
Leia(Q)

    Enquanto (c <= q) faca
         Escreva("Qual o valor em R$: ")
         Leia(R)
         D <- R/2.20
         EscrevaL("O valor que você tem em dólares é U$: ", D:5:2)
         c <- c + 1
    FimEnquanto

fimalgoritmo
