algoritmo "ex26"
// Função :
// Autor :
// Data : 8/2/2023
// Seção de Declarações 
var

N1, N2: inteiro



inicio
// Seção de Comandos 

Escreva("Insira o primeiro número: ")
Leia(N1)
Escreva("Insira o segundo número: ")
Leia(N2)

Se N1 > N2 entao
   Escreva("O primeiro valor é o maior")
FimSe

Se N1 < N2 entao
   Escreva("O segundo valor é o maior")
FimSe

Se N1 = N2 entao
   Escreva("Os dois números são iguais")
FimSe


fimalgoritmo
