algoritmo "semnome"
// Função :
// Autor :
// Data : 8/9/2023
// Seção de Declarações 
var

numero, total, soma : real

inicio
// Seção de Comandos 

numero <- 0
total <- 0
soma <- 0
EscrevaL("Insira somente números inteiros!!!!")

Enquanto (numero < 7) faca
         numero <- numero + 1
         Escreva("Insira o", numero, "o. numero: ")
         Leia(soma)
         total <- total + soma
FimEnquanto

Escreva("A soma dos 7 números inseridos é:" , total)

fimalgoritmo
