algoritmo "semnome"
// Função :
// Autor :
// Data : 8/15/2023
// Seção de Declarações 
var
c, primeiro, tabuada : inteiro

inicio
// Seção de Comandos 

Escreva("A tabuada de que número você quer que eu faça?: ")
Leia(primeiro)
Escreva("Até qual número eu faço a tabuada do", primeiro, "?: ")
Leia(tabuada)

Para c <- 1 ate tabuada passo 1 faca

EscrevaL(primeiro," x", c, " =", c*primeiro)
FimPara
fimalgoritmo
