algoritmo "semnome"
// Função :
// Autor :
// Data : 18/08/2023
// Seção de Declarações 
var

opa : inteiro

Procedimento Escrita(X : caractere ; Y : inteiro)
var c : inteiro

Inicio

EscrevaL("------=======-------")
Para c <- 1 ate opa faca
EscrevaL(x)
FimPara
EscrevaL("------=======-------")


FimProcedimento



inicio
// Seção de Comandos 

Escreva("Quantas vezes é para repetir essa merda? : ")
Leia(opa)
Escrita("Aprendendo Portugol", opa)

fimalgoritmo

