algoritmo "semnome"
// Função :
// Autor :
// Data : 18/08/2023
// Seção de Declarações 
var

a, b : inteiro

Procedimento Somador (x,y : inteiro)
var S : inteiro

Inicio

S <- x + y
Escreva("A soma dos dois números inseridos é: ",S)

FimProcedimento

inicio
// Seção de Comandos 

Escreva("Insira o primeiro número da soma: ")
Leia(a)
Escreva("Insira o segundo número da soma: ")
Leia(b)

Somador(a,b)


fimalgoritmo
