algoritmo "semnome"
// Função :
// Autor :
// Data : 18/08/2023
// Seção de Declarações 
var

A : inteiro

Procedimento ParOuImpar(X : inteiro)
Inicio
     Se (X%2 = 0) entao
     Escreva("O número inserido é PAR")
     Senao
     Escreva("O número inserido é IMPAR")
     FimSe
FimProcedimento

inicio
// Seção de Comandos 

Escreva("Insira um número inteiro: ")
Leia(A)
ParOuImpar(A)


fimalgoritmo
